# -*- coding: utf-8 -*-
"""Entropy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aIjn2MG6-fshgobj23H8Efp7NQsR1MI5
"""

import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

# Load CSV result from model
results = pd.read_csv('/content/colombo_road_patterns.csv')

# Drop NaNs
results_clean = results.dropna(subset=['Prob_G', 'Prob_L', 'Prob_N', 'Prob_O', 'Prob_R', 'Prob_T'])

# Compute entropy
def compute_entropy(row):
    probs = [row[f] for f in ['Prob_G', 'Prob_L', 'Prob_N', 'Prob_O', 'Prob_R', 'Prob_T']]
    probs = np.array(probs)
    probs = probs[probs > 0]  # avoid log(0)
    return -np.sum(probs * np.log2(probs))

results_clean['entropy'] = results_clean.apply(compute_entropy, axis=1)

!pip install contextily

import contextily as ctx

# Load grid shapefile
grid = gpd.read_file("/content/colombo_grid.shp")

# Merge using FID
merged = grid.merge(results_clean[['FID', 'entropy']], left_index=True, right_on='FID')

# Convert to web mercator
merged = merged.to_crs(epsg=3857)



# Plot entropy
fig, ax = plt.subplots(figsize=(14, 14))
merged.plot(column='entropy', ax=ax, cmap='viridis', legend=True, edgecolor='k')
ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik)
ax.set_title("Urban Morphological Entropy in Colombo", fontsize=16)
ax.set_axis_off()
plt.tight_layout()
plt.show()